package com.soap.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-12-14T10:29:51.829-07:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://service.com/", name = "MyServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface MyServiceImpl {

    @WebMethod
    @Action(input = "http://service.com/MyServiceImpl/getProductDetailRequest", output = "http://service.com/MyServiceImpl/getProductDetailResponse")
    @RequestWrapper(localName = "getProductDetail", targetNamespace = "http://service.com/", className = "com.soap.type.GetProductDetail")
    @ResponseWrapper(localName = "getProductDetailResponse", targetNamespace = "http://service.com/", className = "com.soap.type.GetProductDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.soap.type.Product getProductDetail();

    @WebMethod
    @Action(input = "http://service.com/MyServiceImpl/sumRequest", output = "http://service.com/MyServiceImpl/sumResponse")
    @RequestWrapper(localName = "sum", targetNamespace = "http://service.com/", className = "com.soap.type.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://service.com/", className = "com.soap.type.SumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
