package com.soap.type;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-12-14T10:29:51.853-07:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "MyServiceImplService", 
                  wsdlLocation = "file:/C:/Users/rgusida/spring-ws-service-master/src/main/resources/wsdl/MyService.wsdl",
                  targetNamespace = "http://service.com/") 
public class MyServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.com/", "MyServiceImplService");
    public final static QName MyServiceImplPort = new QName("http://service.com/", "MyServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rgusida/spring-ws-service-master/src/main/resources/wsdl/MyService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rgusida/spring-ws-service-master/src/main/resources/wsdl/MyService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MyServiceImpl
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public MyServiceImpl getMyServiceImplPort() {
        return super.getPort(MyServiceImplPort, MyServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyServiceImpl
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public MyServiceImpl getMyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MyServiceImplPort, MyServiceImpl.class, features);
    }

}
